var hira = [
{jp:"あ",ro:["a"]},
{jp:"い",ro:["i"]},
{jp:"う",ro:["u"]},
{jp:"え",ro:["e"]},
{jp:"お",ro:["o"]},
{jp:"か",ro:["ka"]},
{jp:"き",ro:["ki"]},
{jp:"く",ro:["ku"]},
{jp:"け",ro:["ke"]},
{jp:"こ",ro:["ko"]},
{jp:"さ",ro:["sa"]},
{jp:"し",ro:["shi"]},
{jp:"す",ro:["su"]},
{jp:"せ",ro:["se"]},
{jp:"そ",ro:["so"]},
{jp:"た",ro:["ta"]},
{jp:"ち",ro:["chi"]},
{jp:"つ",ro:["tsu"]},
{jp:"て",ro:["te"]},
{jp:"と",ro:["to"]},
{jp:"な",ro:["na"]},
{jp:"に",ro:["ni"]},
{jp:"ぬ",ro:["nu"]},
{jp:"ね",ro:["ne"]},
{jp:"の",ro:["no"]},
{jp:"は",ro:["ha"]},
{jp:"ひ",ro:["hi"]},
{jp:"ふ",ro:["fu"]},
{jp:"へ",ro:["he"]},
{jp:"ほ",ro:["ho"]},
{jp:"ま",ro:["ma"]},
{jp:"み",ro:["mi"]},
{jp:"む",ro:["mu"]},
{jp:"め",ro:["me"]},
{jp:"も",ro:["mo"]},
{jp:"や",ro:["ya"]},
{jp:"ゆ",ro:["yu"]},
{jp:"よ",ro:["yo"]},
{jp:"ら",ro:["ra"]},
{jp:"り",ro:["ri"]},
{jp:"る",ro:["ru"]},
{jp:"れ",ro:["re"]},
{jp:"ろ",ro:["ro"]},
{jp:"わ",ro:["wa"]},
{jp:"ん",ro:["n"]},
{jp:"を",ro:["wo"]}
];

var hira_zv = [
{jp:"が",ro:["ga"]},
{jp:"ぎ",ro:["gi"]},
{jp:"ぐ",ro:["gu"]},
{jp:"げ",ro:["ge"]},
{jp:"ご",ro:["go"]},
{jp:"ざ",ro:["za"]},
{jp:"じ",ro:["ji", "zi"]},
{jp:"ず",ro:["zu"]},
{jp:"ぜ",ro:["ze"]},
{jp:"ぞ",ro:["zo"]},
{jp:"だ",ro:["da"]},
{jp:"ぢ",ro:["di", "ji"]},
{jp:"づ",ro:["du", "dzu"]},
{jp:"で",ro:["de"]},
{jp:"ど",ro:["do"]},
{jp:"ば",ro:["ba"]},
{jp:"び",ro:["bi"]},
{jp:"ぶ",ro:["bu"]},
{jp:"べ",ro:["be"]},
{jp:"ぼ",ro:["bo"]},
{jp:"ぱ",ro:["pa"]},
{jp:"ぴ",ro:["pi"]},
{jp:"ぷ",ro:["pu"]},
{jp:"ぺ",ro:["pe"]},
{jp:"ぽ",ro:["po"]}
];

var hira_yo = [
{jp:"きゃ",ro:["kya"]},
{jp:"きゅ",ro:["kyu"]},
{jp:"きょ",ro:["kyo"]},
{jp:"しゃ",ro:["sha"]},
{jp:"しゅ",ro:["shu"]},
{jp:"しょ",ro:["sho"]},
{jp:"ちゃ",ro:["cha"]},
{jp:"ちゅ",ro:["chu"]},
{jp:"ちょ",ro:["cho"]},
{jp:"にゃ",ro:["nya"]},
{jp:"にゅ",ro:["nyu"]},
{jp:"にょ",ro:["nyo"]},
{jp:"ひゃ",ro:["hya"]},
{jp:"ひゅ",ro:["hyu"]},
{jp:"ひょ",ro:["hyo"]},
{jp:"みゃ",ro:["mya"]},
{jp:"みゅ",ro:["myu"]},
{jp:"みょ",ro:["myo"]},
{jp:"りゃ",ro:["rya"]},
{jp:"りゅ",ro:["ryu"]},
{jp:"りょ",ro:["ryo"]},
{jp:"ぎゃ",ro:["gya"]},
{jp:"ぎゅ",ro:["gyu"]},
{jp:"ぎょ",ro:["gyo"]},
{jp:"じゃ",ro:["ja"]},
{jp:"じゅ",ro:["ju"]},
{jp:"じょ",ro:["jo"]},
{jp:"ぢゃ",ro:["dya", "ja"]},
{jp:"ぢゅ",ro:["dyu", "ju"]},
{jp:"ぢょ",ro:["dyo", "jo"]},
{jp:"びゃ",ro:["bya"]},
{jp:"びゅ",ro:["byu"]},
{jp:"びょ",ro:["byo"]},
{jp:"ぴゃ",ro:["pya"]},
{jp:"ぴゅ",ro:["pyu"]},
{jp:"ぴょ",ro:["pyo"]}
];

var kana_dicts = [
{name:"", dict:"hira"},
{name:"", dict:"hira_zv"},
{name:"", dict:"hira_yo"},
{name:"", dict:"kata"},
{name:"", dict:"kata_zv"},
{name:"", dict:"kata_yo"},
];
