var basic = [
{jp:"一",ro:["ichi"]},
{jp:"二",ro:["ni"]},
{jp:"三",ro:["san"]},
{jp:"十",ro:["juu"]},
{jp:"土",ro:["tsuchi"]},
{jp:"口",ro:["kuchi"]},
{jp:"古い",ro:["furui"]},
{jp:"日",ro:["hi"]},
{jp:"目",ro:["me"]},
{jp:"田",ro:["ta"]},
{jp:"中",ro:["naka"]},
{jp:"車",ro:["kuruma"]},
{jp:"山",ro:["yama"]},
{jp:"出ます",ro:["demasu","demas"]},
{jp:"川",ro:["kawa"]},
{jp:"月",ro:["tsuki"]},
{jp:"円",ro:["en"]},
{jp:"人",ro:["hito"]},
{jp:"大きい",ro:["ookii"]},
{jp:"火",ro:["hi"]},
{jp:"八",ro:["hachi"]},
{jp:"分",ro:["fun"]},
{jp:"父",ro:["chichi"]},
{jp:"小さい",ro:["chiisai"]},
{jp:"少ない",ro:["sukunai"]},
{jp:"水",ro:["mizu", "midzu"]},
{jp:"木",ro:["ki"]},
{jp:"本",ro:["hon"]},
{jp:"東",ro:["higashi"]},
{jp:"東京",ro:["toukyou"]},
{jp:"見ます",ro:["mimasu", "mimas"]},
{jp:"先生",ro:["sensei"]},
{jp:"手",ro:["te"]},
{jp:"子ども",ro:["kodomo"]}
];

var unit_1 = [
{jp:"日",ro:["hi"]},
{jp:"月",ro:["tsuki"]},
{jp:"火",ro:["hi"]},
{jp:"水",ro:["mizu"]},
{jp:"木",ro:["ki"]},
{jp:"金",ro:["kane"]},
{jp:"土",ro:["tsuchi"]},
{jp:"山",ro:["yama"]},
{jp:"川",ro:["kawa"]},
{jp:"田",ro:["ta"]},
{jp:"日曜日",ro:["nichiyoubi"]},
{jp:"月曜日",ro:["getsuyoubi"]},
{jp:"火曜日",ro:["kayoubi"]},
{jp:"水曜日",ro:["suiyoubi"]},
{jp:"木曜日",ro:["mokuyoubi"]},
{jp:"金曜日",ro:["kinyoubi"]},
{jp:"土曜日",ro:["doyoubi"]}
];

var unit_2 = [
{jp:"一",ro:["ichi"]},
{jp:"二",ro:["ni"]},
{jp:"三",ro:["san"]},
{jp:"四",ro:["yon", "shi"]},
{jp:"五",ro:["go"]},
{jp:"六",ro:["roku"]},
{jp:"七",ro:["nana", "shichi"]},
{jp:"八",ro:["hachi"]},
{jp:"九",ro:["kyuu", "ku"]},
{jp:"十",ro:["juu"]},
{jp:"百",ro:["hyaku"]},
{jp:"千",ro:["sen"]},
{jp:"万",ro:["man"]},
{jp:"円",ro:["en"]},
{jp:"四月",ro:["shigatsu"]},
{jp:"七月",ro:["shichigatsu"]},
{jp:"一日",ro:["tsuitachi"]},
{jp:"二日",ro:["futsuka"]},
{jp:"三日",ro:["mikka"]},
{jp:"四日",ro:["yokka"]},
{jp:"五日",ro:["itsuka"]},
{jp:"六日",ro:["muika"]},
{jp:"七日",ro:["nanoka"]},
{jp:"八日",ro:["youka"]},
{jp:"九日",ro:["kokonoka"]},
{jp:"十日",ro:["tooka"]},
{jp:"十四日",ro:["juuyokka"]},
{jp:"二十日",ro:["hatsuka"]},
{jp:"二十四日",ro:["nijuuyokka"]},
{jp:"三百",ro:["sanbyaku"]},
{jp:"六百",ro:["roppyaku"]},
{jp:"八百",ro:["happyaku"]},
{jp:"三千",ro:["sanzen"]},
{jp:"八千",ro:["hassen"]}
];

var unit_3 = [
{jp:"学",ro:["gaku"]},
{jp:"大学",ro:["daigaku"]},
{jp:"学生",ro:["gakusei"]},
{jp:"先生",ro:["sensei"]},
{jp:"先月",ro:["sengetsu"]},
{jp:"会社",ro:["kaisha"]},
{jp:"会社員",ro:["kaishain"]},
{jp:"医者",ro:["isha"]},
{jp:"本",ro:["hon"]},
{jp:"日本",ro:["nihon"]},
{jp:"中",ro:["naka"]},
{jp:"国",ro:["kuni"]},
{jp:"中国",ro:["chuugoku"]},
{jp:"人",ro:["hito"]},
{jp:"日本人",ro:["nihonjin"]}
];

var unit_4 = [
{jp:"今", ro:["ima"]},
{jp:"今日", ro:["kyou"]},
{jp:"今週", ro:["konshuu"]},
{jp:"今月", ro:["kongetsu"]},
{jp:"今年", ro:["kotoshi"]},
{jp:"朝", ro:["asa"]},
{jp:"昼", ro:["hiru"]},
{jp:"晩", ro:["ban"]},
{jp:"今朝", ro:["kesa"]},
{jp:"今晩", ro:["konban", "komban"]},
{jp:"四時", ro:["yoji"]},
{jp:"七時", ro:["shichiji"]},
{jp:"九時", ro:["kuji"]},
{jp:"一分", ro:["ippun"]},
{jp:"二分", ro:["nifun"]},
{jp:"三分", ro:["sanpun"]},
{jp:"四分", ro:["yonpun"]},
{jp:"五分", ro:["gofun"]},
{jp:"六分", ro:["roppun"]},
{jp:"七分", ro:["nanafun", "shichifun"]},
{jp:"八分", ro:["happun"]},
{jp:"九分", ro:["kyuufun"]},
{jp:"十分", ro:["juppun", "jippun"]},
{jp:"半", ro:["han"]},
{jp:"午前", ro:["gozen"]},
{jp:"午後", ro:["gogo"]},
{jp:"休み", ro:["yasumi"]},
{jp:"毎日", ro:["mainichi"]},
{jp:"毎週", ro:["maishuu"]},
{jp:"毎月", ro:["maitsuki"]},
{jp:"毎年", ro:["maitoshi", "mainen"]},
{jp:"毎朝", ro:["maiasa"]},
{jp:"毎晩", ro:["maiban"]},
{jp:"何", ro:["nani", "nan"]}
];

var unit_5 = [
{jp:"行きます", ro:["ikimasu", "ikimas"]},
{jp:"来ます", ro:["kimasu", "kimas"]},
{jp:"学校", ro:["gakkou"]},
{jp:"先週", ro:["senshuu"]},
{jp:"今週", ro:["konshuu"]},
{jp:"来週", ro:["raishuu"]},
{jp:"去年", ro:["kyonen"]},
{jp:"今年", ro:["kotoshi"]},
{jp:"来年", ro:["rainen"]},
{jp:"来月", ro:["raigetsu"]},
{jp:"駅", ro:["eki"]},
{jp:"電車", ro:["densha"]},
{jp:"自転車", ro:["jitensha"]},
{jp:"自動車", ro:["jidousha"]}
];

var unit_6 = [
{jp:"高い", ro:["takai"]},
{jp:"安い", ro:["yasui"]},
{jp:"大きい", ro:["ookii"]},
{jp:"小さい", ro:["chiisai"]},
{jp:"大学", ro:["daigaku"]},
{jp:"大学生", ro:["daigakusei"]},
{jp:"新しい", ro:["atarashii"]},
{jp:"古い", ro:["furui"]},
{jp:"新聞", ro:["shinbun", "shimbun"]},
{jp:"白い", ro:["shiroi"]},
{jp:"青い", ro:["aoi"]},
{jp:"赤い", ro:["akai"]},
{jp:"黒い", ro:["kuroi"]}
];

var unit_7 = [
{jp:"上", ro:["ue"]},
{jp:"下", ro:["shita"]},
{jp:"父", ro:["chichi"]},
{jp:"母", ro:["haha"]},
{jp:"お父さん", ro:["otousan"]},
{jp:"お母さん", ro:["okaasan"]},
{jp:"子ども", ro:["kodomo"]},
{jp:"上手", ro:["jouzu"]},
{jp:"下手", ro:["heta"]},
{jp:"手", ro:["te"]},
{jp:"好きな", ro:["sukina", "skina"]},
{jp:"主人", ro:["shujin"]},
{jp:"肉", ro:["niku"]},
{jp:"魚", ro:["sakana"]},
{jp:"食べます", ro:["tabemasu", "tabemas"]},
{jp:"飲みます", ro:["nomimasu", "nomimas"]},
{jp:"物", ro:["mono"]},
{jp:"食べ物", ro:["tabemono"]},
{jp:"飲み物", ro:["nomimono"]}
];

var unit_8 = [
{jp:"近く", ro:["chikaku"]},
{jp:"間", ro:["aida"]},
{jp:"時間", ro:["jikan"]},
{jp:"右", ro:["migi"]},
{jp:"左", ro:["hidari"]},
{jp:"前", ro:["mae"]},
{jp:"後ろ", ro:["ushiro"]},
{jp:"外", ro:["soto"]},
{jp:"男の子", ro:["otokonoko"]},
{jp:"女の人", ro:["onnanohito"]},
{jp:"犬", ro:["inu"]}
];

var unit_9 = [
{jp:"書きます", ro:["kakimasu", "kakimas"]},
{jp:"聞きます", ro:["kikimasu", "kikimas"]},
{jp:"読みます", ro:["yomimasu", "yomimas"]},
{jp:"見ます", ro:["mimasu", "mimas"]},
{jp:"電話", ro:["denwa"]},
{jp:"買います", ro:["kaimasu", "kaimas"]},
{jp:"起きます", ro:["okimasu", "okimas"]},
{jp:"帰ります", ro:["kaerimasu", "kaerimas"]},
{jp:"友達", ro:["tomodachi"]},
{jp:"会います", ro:["aimasu", "aimas"]},
{jp:"新聞", ro:["shinbun", "shimbun"]}
];

var unit_10 = [
{jp:"お茶", ro:["ocha"]},
{jp:"お酒", ro:["osake"]},
{jp:"写真", ro:["shashin"]},
{jp:"紙", ro:["kami"]},
{jp:"手紙", ro:["tegami"]},
{jp:"映画", ro:["eiga"]},
{jp:"英語", ro:["eigo"]},
{jp:"店", ro:["mise"]}
];

var unit_11 = [
{jp:"送ります", ro:["okurimasu", "okurimas"]},
{jp:"切ります", ro:["kirimasu", "kirimas"]},
{jp:"切手", ro:["kitte"]},
{jp:"貸します", ro:["kashimasu", "kashimas"]},
{jp:"借ります", ro:["karimasu", "karimas"]},
{jp:"旅行", ro:["ryokou"]},
{jp:"教えます", ro:["oshiemasu", "oshiemas"]},
{jp:"習います", ro:["naraimasu", "naraimas"]},
{jp:"勉強", ro:["benkyou"]},
{jp:"花", ro:["hana"]}
];

var kanji_dicts = [
{name:"Basic Strokes", dict:"basic"},
{name:"ユニット１", dict:"unit_1"},
{name:"ユニット２", dict:"unit_2"},
{name:"ユニット３", dict:"unit_3"},
{name:"ユニット４", dict:"unit_4"},
{name:"ユニット５", dict:"unit_5"},
{name:"ユニット６", dict:"unit_6"},
{name:"ユニット７", dict:"unit_7"},
{name:"ユニット８", dict:"unit_8"},
{name:"ユニット９", dict:"unit_9"},
{name:"ユニット１０", dict:"unit_10"},
{name:"ユニット１１", dict:"unit_11"},
];
