var basic = [
{jp:"一",ro:["ichi"]},
{jp:"二",ro:["ni"]},
{jp:"三",ro:["san"]},
{jp:"十",ro:["juu"]},
{jp:"土",ro:["tsuchi"]},
{jp:"口",ro:["kuchi"]},
{jp:"古い",ro:["furui"]},
{jp:"日",ro:["hi"]},
{jp:"目",ro:["me"]},
{jp:"田",ro:["ta"]},
{jp:"中",ro:["naka"]},
{jp:"車",ro:["kuruma"]},
{jp:"山",ro:["yama"]},
{jp:"出ます",ro:["demasu","demas"]},
{jp:"川",ro:["kawa"]},
{jp:"月",ro:["tsuki"]},
{jp:"円",ro:["en"]},
{jp:"人",ro:["hito"]},
{jp:"大きい",ro:["ookii"]},
{jp:"火",ro:["hi"]},
{jp:"八",ro:["hachi"]},
{jp:"分",ro:["fun"]},
{jp:"父",ro:["chichi"]},
{jp:"小さい",ro:["chiisai"]},
{jp:"少ない",ro:["sukunai"]},
{jp:"水",ro:["mizu", "midzu"]},
{jp:"木",ro:["ki"]},
{jp:"本",ro:["hon"]},
{jp:"東",ro:["higashi"]},
{jp:"東京",ro:["toukyou", "tookyoo"]},
{jp:"見ます",ro:["mimasu", "mimas"]},
{jp:"先生",ro:["sensei"]},
{jp:"手",ro:["te"]},
{jp:"子ども",ro:["kodomo"]}
];

var unit_1 = [
{jp:"日",ro:["hi"]},
{jp:"月",ro:["tsuki"]},
{jp:"火",ro:["hi"]},
{jp:"水",ro:["mizu"]},
{jp:"木",ro:["ki"]},
{jp:"金",ro:["kane"]},
{jp:"土",ro:["tsuchi"]},
{jp:"山",ro:["yama"]},
{jp:"川",ro:["kawa"]},
{jp:"田",ro:["ta"]},
{jp:"日曜日",ro:["nichiyoubi"]},
{jp:"月曜日",ro:["getsuyoubi"]},
{jp:"火曜日",ro:["kayoubi"]},
{jp:"水曜日",ro:["suiyoubi"]},
{jp:"木曜日",ro:["mokuyoubi"]},
{jp:"金曜日",ro:["kinyoubi"]},
{jp:"土曜日",ro:["doyoubi"]}
];

var unit_2 = [
{jp:"一",ro:["ichi"]},
{jp:"二",ro:["ni"]},
{jp:"三",ro:["san"]},
{jp:"四",ro:["yon", "shi"]},
{jp:"五",ro:["go"]},
{jp:"六",ro:["roku"]},
{jp:"七",ro:["nana", "shichi"]},
{jp:"八",ro:["hachi"]},
{jp:"九",ro:["kyuu", "ku"]},
{jp:"十",ro:["juu"]},
{jp:"百",ro:["hyaku"]},
{jp:"千",ro:["sen"]},
{jp:"万",ro:["man"]},
{jp:"円",ro:["en"]},
{jp:"四月",ro:["shigatsu"]},
{jp:"七月",ro:["shichigatsu"]},
{jp:"一日",ro:["tsuitachi"]},
{jp:"二日",ro:["futsuka"]},
{jp:"三日",ro:["mikka"]},
{jp:"四日",ro:["yokka"]},
{jp:"五日",ro:["itsuka"]},
{jp:"六日",ro:["muika"]},
{jp:"七日",ro:["nanoka"]},
{jp:"八日",ro:["youka"]},
{jp:"九日",ro:["kokonoka"]},
{jp:"十日",ro:["tooka"]},
{jp:"十四日",ro:["juuyokka"]},
{jp:"二十日",ro:["hatsuka"]},
{jp:"二十四日",ro:["nijuuyokka"]},
{jp:"三百",ro:["sanbyaku"]},
{jp:"六百",ro:["roppyaku"]},
{jp:"八百",ro:["happyaku"]},
{jp:"三千",ro:["sanzen"]},
{jp:"八千",ro:["hassen"]}
];
