var basic = [
{jp:"一",ro:["ichi"]},
{jp:"二",ro:["ni"]},
{jp:"三",ro:["san"]},
{jp:"十",ro:["juu"]},
{jp:"土",ro:["tsuchi"]},
{jp:"口",ro:["kuchi"]},
{jp:"古い",ro:["furui"]},
{jp:"日",ro:["hi"]},
{jp:"目",ro:["me"]},
{jp:"田",ro:["ta"]},
{jp:"中",ro:["naka"]},
{jp:"車",ro:["kuruma"]},
{jp:"山",ro:["yama"]},
{jp:"出ます",ro:["demasu","demas"]},
{jp:"川",ro:["kawa"]},
{jp:"月",ro:["tsuki"]},
{jp:"円",ro:["en"]},
{jp:"人",ro:["hito"]},
{jp:"大きい",ro:["ookii"]},
{jp:"火",ro:["hi"]},
{jp:"八",ro:["hachi"]},
{jp:"分",ro:["fun"]},
{jp:"父",ro:["chichi"]},
{jp:"小さい",ro:["chiisai"]},
{jp:"少ない",ro:["sukunai"]},
{jp:"水",ro:["mizu", "midzu"]},
{jp:"木",ro:["ki"]},
{jp:"本",ro:["hon"]},
{jp:"東",ro:["higashi"]},
{jp:"東京",ro:["toukyou", "tookyoo"]},
{jp:"見ます",ro:["mimasu", "mimas"]},
{jp:"先生",ro:["sensei"]},
{jp:"手",ro:["te"]},
{jp:"子ども",ro:["kodomo"]}
];

var unit_1 = [
{jp:"日",ro:["hi"]},
{jp:"月",ro:["tsuki"]},
{jp:"火",ro:["hi"]},
{jp:"水",ro:["mizu"]},
{jp:"木",ro:["ki"]},
{jp:"金",ro:["kane"]},
{jp:"土",ro:["tsuchi"]},
{jp:"山",ro:["yama"]},
{jp:"川",ro:["kawa"]},
{jp:"田",ro:["ta"]},
{jp:"日曜日",ro:["nichiyoubi"]},
{jp:"月曜日",ro:["getsuyoubi"]},
{jp:"火曜日",ro:["kayoubi"]},
{jp:"水曜日",ro:["suiyoubi"]},
{jp:"木曜日",ro:["mokuyoubi"]},
{jp:"金曜日",ro:["kinyoubi"]},
{jp:"土曜日",ro:["doyoubi"]}
];

var unit_2 = [
{jp:"一",ro:["ichi"]},
{jp:"二",ro:["ni"]},
{jp:"三",ro:["san"]},
{jp:"四",ro:["yon", "shi"]},
{jp:"五",ro:["go"]},
{jp:"六",ro:["roku"]},
{jp:"七",ro:["nana", "shichi"]},
{jp:"八",ro:["hachi"]},
{jp:"九",ro:["kyuu", "ku"]},
{jp:"十",ro:["juu"]},
{jp:"百",ro:["hyaku"]},
{jp:"千",ro:["sen"]},
{jp:"万",ro:["man"]},
{jp:"円",ro:["en"]},
{jp:"四月",ro:["shigatsu"]},
{jp:"七月",ro:["shichigatsu"]},
{jp:"一日",ro:["tsuitachi"]},
{jp:"二日",ro:["futsuka"]},
{jp:"三日",ro:["mikka"]},
{jp:"四日",ro:["yokka"]},
{jp:"五日",ro:["itsuka"]},
{jp:"六日",ro:["muika"]},
{jp:"七日",ro:["nanoka"]},
{jp:"八日",ro:["youka"]},
{jp:"九日",ro:["kokonoka"]},
{jp:"十日",ro:["tooka"]},
{jp:"十四日",ro:["juuyokka"]},
{jp:"二十日",ro:["hatsuka"]},
{jp:"二十四日",ro:["nijuuyokka"]},
{jp:"三百",ro:["sanbyaku"]},
{jp:"六百",ro:["roppyaku"]},
{jp:"八百",ro:["happyaku"]},
{jp:"三千",ro:["sanzen"]},
{jp:"八千",ro:["hassen"]}
];

var unit_3 = [
{jp:"学",ro:["gaku"]},
{jp:"大学",ro:["daigaku"]},
{jp:"学生",ro:["gakusei"]},
{jp:"先生",ro:["sensei"]},
{jp:"先月",ro:["sengetsu"]},
{jp:"会社",ro:["kaisha"]},
{jp:"会社員",ro:["kaishain"]},
{jp:"医者",ro:["isha"]},
{jp:"本",ro:["hon"]},
{jp:"日本",ro:["nihon"]},
{jp:"中",ro:["naka"]},
{jp:"国",ro:["kuni"]},
{jp:"中国",ro:["chuugoku"]},
{jp:"人",ro:["hito"]},
{jp:"日本人",ro:["nihonjin"]}
];

var unit_4 = [
{jp:"今", ro:["ima"]},
{jp:"今日", ro:["kyou"]},
{jp:"今週", ro:["konshuu"]},
{jp:"今月", ro:["kongetsu"]},
{jp:"今年", ro:["kotoshi"]},
{jp:"朝", ro:["asa"]},
{jp:"昼", ro:["hiru"]},
{jp:"晩", ro:["ban"]},
{jp:"今朝", ro:["kesa"]},
{jp:"今晩", ro:["konban", "komban"]},
{jp:"四時", ro:["yoji"]},
{jp:"七時", ro:["shichiji"]},
{jp:"九時", ro:["kuji"]},
{jp:"一分", ro:["ippun"]},
{jp:"二分", ro:["nifun"]},
{jp:"三分", ro:["sanpun"]},
{jp:"四分", ro:["yonpun"]},
{jp:"五分", ro:["gofun"]},
{jp:"六分", ro:["roppun"]},
{jp:"七分", ro:["nanafun", "shichifun"]},
{jp:"八分", ro:["happun"]},
{jp:"九分", ro:["kyuufun"]},
{jp:"十分", ro:["juppun", "jippun"]},
{jp:"半", ro:["han"]},
{jp:"午前", ro:["gozen"]},
{jp:"午後", ro:["gogo"]},
{jp:"休み", ro:["yasumi"]},
{jp:"毎日", ro:["mainichi"]},
{jp:"毎週", ro:["maishuu"]},
{jp:"毎月", ro:["maitsuki"]},
{jp:"毎年", ro:["maitoshi", "mainen"]},
{jp:"毎朝", ro:["maiasa"]},
{jp:"毎晩", ro:["maiban"]},
{jp:"何", ro:["nani", "nan"]}
];

var kanji_dicts =["basic", "unit_1", "unit_2", "unit_3", "unit_4"];
