var kata = [
{jp:"ア",ro:["a"]},
{jp:"イ",ro:["i"]},
{jp:"ウ",ro:["u"]},
{jp:"エ",ro:["e"]},
{jp:"オ",ro:["o"]},
{jp:"カ",ro:["ka"]},
{jp:"キ",ro:["ki"]},
{jp:"ク",ro:["ku"]},
{jp:"ケ",ro:["ke"]},
{jp:"コ",ro:["ko"]},
{jp:"サ",ro:["sa"]},
{jp:"シ",ro:["shi"]},
{jp:"ス",ro:["su"]},
{jp:"セ",ro:["se"]},
{jp:"ソ",ro:["so"]},
{jp:"タ",ro:["ta"]},
{jp:"チ",ro:["chi"]},
{jp:"ツ",ro:["tsu"]},
{jp:"テ",ro:["te"]},
{jp:"ト",ro:["to"]},
{jp:"ナ",ro:["na"]},
{jp:"ニ",ro:["ni"]},
{jp:"ヌ",ro:["nu"]},
{jp:"ネ",ro:["ne"]},
{jp:"ノ",ro:["no"]},
{jp:"ハ",ro:["ha"]},
{jp:"ヒ",ro:["hi"]},
{jp:"フ",ro:["fu"]},
{jp:"ヘ",ro:["he"]},
{jp:"ホ",ro:["ho"]},
{jp:"マ",ro:["ma"]},
{jp:"ミ",ro:["mi"]},
{jp:"ム",ro:["mu"]},
{jp:"メ",ro:["me"]},
{jp:"モ",ro:["mo"]},
{jp:"ヤ",ro:["ya"]},
{jp:"ユ",ro:["yu"]},
{jp:"ヨ",ro:["yo"]},
{jp:"ラ",ro:["ra"]},
{jp:"リ",ro:["ri"]},
{jp:"ル",ro:["ru"]},
{jp:"レ",ro:["re"]},
{jp:"ロ",ro:["ro"]},
{jp:"ワ",ro:["wa"]},
{jp:"ン",ro:["n"]},
{jp:"ヲ",ro:["wo"]}
];

var kata_zv = [
{jp:"ガ",ro:["ga"]},
{jp:"ギ",ro:["gi"]},
{jp:"グ",ro:["gu"]},
{jp:"ゲ",ro:["ge"]},
{jp:"ゴ",ro:["go"]},
{jp:"ザ",ro:["za"]},
{jp:"ジ",ro:["ji", "zi"]},
{jp:"ズ",ro:["zu"]},
{jp:"ゼ",ro:["ze"]},
{jp:"ゾ",ro:["zo"]},
{jp:"ダ",ro:["da"]},
{jp:"ヂ",ro:["di", "ji"]},
{jp:"ヅ",ro:["du", "dzu"]},
{jp:"デ",ro:["de"]},
{jp:"ド",ro:["do"]},
{jp:"バ",ro:["ba"]},
{jp:"ビ",ro:["bi"]},
{jp:"ブ",ro:["bu"]},
{jp:"ベ",ro:["be"]},
{jp:"ボ",ro:["bo"]},
{jp:"パ",ro:["pa"]},
{jp:"ピ",ro:["pi"]},
{jp:"プ",ro:["pu"]},
{jp:"ペ",ro:["pe"]},
{jp:"ポ",ro:["po"]}
];

var kata_yo = [
{jp:"キャ",ro:["kya"]},
{jp:"キュ",ro:["kyu"]},
{jp:"キョ",ro:["kyo"]},
{jp:"シャ",ro:["sha"]},
{jp:"シュ",ro:["shu"]},
{jp:"ショ",ro:["sho"]},
{jp:"チャ",ro:["cha"]},
{jp:"チュ",ro:["chu"]},
{jp:"チョ",ro:["cho"]},
{jp:"ニャ",ro:["nya"]},
{jp:"ニュ",ro:["nyu"]},
{jp:"ニョ",ro:["nyo"]},
{jp:"ヒャ",ro:["hya"]},
{jp:"ヒュ",ro:["hyu"]},
{jp:"ヒョ",ro:["hyo"]},
{jp:"ミャ",ro:["mya"]},
{jp:"ミュ",ro:["myu"]},
{jp:"ミョ",ro:["myo"]},
{jp:"リャ",ro:["rya"]},
{jp:"リュ",ro:["ryu"]},
{jp:"リョ",ro:["ryo"]},
{jp:"ギャ",ro:["gya"]},
{jp:"ギュ",ro:["gyu"]},
{jp:"ギョ",ro:["gyo"]},
{jp:"ジャ",ro:["ja"]},
{jp:"ジュ",ro:["ju"]},
{jp:"ジョ",ro:["jo"]},
{jp:"ヂャ",ro:["dya", "ja"]},
{jp:"ヂュ",ro:["dyu", "ju"]},
{jp:"ヂョ",ro:["dyo", "jo"]},
{jp:"ビャ",ro:["bya"]},
{jp:"ビュ",ro:["byu"]},
{jp:"ビョ",ro:["byo"]},
{jp:"ピャ",ro:["pya"]},
{jp:"ピュ",ro:["pyu"]},
{jp:"ピョ",ro:["pyo"]}
];
